### ISSUE TITLE
Malformed PE image generation

### ISSUE THREAD

**Issue by mhaeuser** [rhboot/shim#360]
Please refer to the gnu-efi upstream bug: https://sourceforge.net/p/gnu-efi/bugs/27/

Sorry to ask, but why does this project use gnu-efi over EDK II? I am currently contributing to EDK II and looking at how niche the space is, validation becomes much harder with fragmentation. I understand that not everyone is happy with EDK II, but so far from the two alternative solutions (gnu-efi and elf2efi) I have been confronted with, both generate malformed binaries.

**Comment by xnox** [comment]
Please use the vendored gnu-efi inside the shim project itself.

We might stop using gnu-efi in the future and do everything we need ourselves, i.e. just like grub does.

**Comment by mhaeuser** [comment]
@xnox You do not rebase to upstream? Well, ok.

Do you have any idea about the non-consecutive section layout? I'm unfortunately not proficient with your build system. iPXE uses an ELF to PE32 conversion which we fixed up recently, if you do something similar, maybe a common solution would be good?

**Comment by xnox** [comment]
> @xnox You do not rebase to upstream? Well, ok.
> 

No, fixed in time & features, with many fixes.

> Do you have any idea about the non-consecutive section layout? I'm unfortunately not proficient with your build system. iPXE uses an ELF to PE32 conversion which we fixed up recently, if you do something similar, maybe a common solution would be good?

Some, but not all. See our elf_* scripts at the top level of https://github.com/rhboot/shim

**Comment by aronowski** [comment]
@mhaeuser, I can see your upstream ticket has been closed and the appropriate changes have been introduced.

Is there something we're still waiting for in this issue?

**Comment by mhaeuser** [comment]
@aronowski, sorry, I somehow didn't get notified about your reply. Well, the changes were not submitted and not rebased by https://github.com/rhboot/gnu-efi, so the issue is still valid and open. But for now, I don't plan to submit the fixes to rhboot, because I no longer have a testing environment set up.
